name: functions_framework_builder
version: 0.3.1
description: Builder for package:functions_framework
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analyzer: '>=0.40.6 <0.42.0'
  build: ^1.3.0
  build_config: ^0.4.3
  dart_style: ^1.3.10
  # There is a tight version constraint because the builder has a strict
  # dependency on all features exposed.
  functions_framework: '>=0.3.0 <0.3.2'
  glob: ^1.2.0
  meta: ^1.2.4
  path: ^1.7.0
  shelf: ^0.7.9
  source_gen: ^0.9.8

dev_dependencies:
  build_test: ^1.3.0
  package_config: ^1.9.3
  stream_transform: ^1.2.0
  test: ^1.15.7
