name: functions_framework_builder
version: 0.4.11-wip
description: Builder for package:functions_framework
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  analyzer: '>=9.0.0 <11.0.0'
  build: ^4.0.3
  build_config: ^1.2.0
  collection: ^1.19.0
  dart_style: ^3.1.3
  # There is a tight version constraint because the builder has a strict
  # dependency on all features exposed.
  functions_framework: ">=0.4.0 <0.4.5"
  glob: ^2.1.2
  meta: ^1.17.0
  path: ^1.9.0
  shelf: ^1.4.0
  source_gen: ^4.1.1
  source_helper: ^1.3.9

dev_dependencies:
  build_test: ^3.5.4
  dart_flutter_team_lints: ^3.2.0
  logging: ^1.2.0
  stream_transform: ^2.0.0
  test: ^1.27.0
