name: functions_framework_builder
description: Builder for package:functions_framework
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  build: ^1.3.0
  # Because this package has a build.yaml file
  build_config: ^0.4.3
  functions_framework: any
  glob: ^1.2.0
  path: ^1.7.0
  source_gen: ^0.9.8

dependency_overrides:
  functions_framework:
    path: ../functions_framework
