name: functions_framework_builder
version: 0.4.11-wip
description: Builder for package:functions_framework
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.4.0
  build: ^4.0.2
  build_config: ^1.0.0
  collection: ^1.17.0
  dart_style: '>=2.3.7 <4.0.0'
  # There is a tight version constraint because the builder has a strict
  # dependency on all features exposed.
  functions_framework: '>=0.4.0 <0.4.5'
  glob: ^2.0.0
  meta: ^1.7.0
  path: ^1.8.0
  shelf: ^1.0.0
  source_gen: ^4.0.2
  source_helper: ^1.3.3

dev_dependencies:
  build_test: ^3.0.0
  dart_flutter_team_lints: ^3.0.0
  package_config: ^2.0.0
  stream_transform: ^2.0.0
  test: ^1.21.6
