name: google_cloud
description: >-
  Utilities for running Dart code correctly on the Google Cloud Platform.
version: 0.3.0-wip
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/google_cloud

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.0
  http: ^1.1.0
  io: ^1.0.3
  meta: ^1.18.1
  shelf: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  dart_flutter_team_lints: ^3.2.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  test: ^1.27.0
  test_process: ^2.0.3
