name: hello_world_function
version: 0.4.0
description: Dart Functions Framework simple function example.
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_flutter_team_lints: ^3.0.0
  functions_framework_builder: ^0.4.1
  http: '>=0.13.0 <2.0.0'
  test: ^1.16.6
  test_process: ^2.0.0
