name: hello_world_function_test
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  functions_framework: any
  json_annotation: ^4.3.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  functions_framework_builder: any
  http: ^0.13.1
  http_parser: ^4.0.0
  io: ^1.0.0
  json_serializable: ^6.0.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0

dependency_overrides:
  functions_framework:
    path: ../functions_framework
  functions_framework_builder:
    path: ../functions_framework_builder
