name: hello_world_function_test
publish_to: none

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  functions_framework: ^0.4.3+1
  json_annotation: ^4.9.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: ^2.2.1
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^3.0.0
  google_cloud: ^0.2.1-wip
  http: ^1.0.0
  http_parser: ^4.0.0
  io: ^1.0.3
  json_serializable: ^6.6.0
  test: ^1.21.6
  test_process: ^2.0.0
