name: functions_framework_tool
description: >
  A tools package for managing FaaS (Function as a service) portable Dart functions projects
# After changing the version, run `pub run build_runner build`.
version: 0.3.0
homepage: https://github.com/GoogleCloudPlatform/functions-framework-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

executables:
  dartfn:

dependencies:
  args: ^1.6.0
  build: ^1.5.2
  glob: ^1.2.0
  http: ^0.12.2
  io: ^0.3.4
  path: ^1.7.0
  pedantic: ^1.9.2
  stagehand: ^3.3.11
  source_gen: ^0.9.5
  usage: ^3.4.2

dev_dependencies:
  build_config: ^0.4.5
  build_runner: ^1.10.7
  build_verify: ^1.1.1
  build_version: ^2.0.1
  grinder: ^0.8.6
  test: ^1.15.7
  yaml: ^2.2.1
