name: backend
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  functions_framework: ^0.4.0
  json_annotation: ^4.9.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: ^2.10.4
  dart_flutter_team_lints: ^3.2.0
  functions_framework_builder: ^0.4.7
  http: ^1.1.0
  json_serializable: ^6.11.3
  test: ^1.27.0
  test_process: ^2.0.3
