name: example_protobuf_firestore
publish_to: none

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  functions_framework: ^0.4.3
  protobuf: ^5.0.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: ^2.2.1
  dart_flutter_team_lints: ^3.0.0
  functions_framework_builder: ^0.4.10
  http: ^1.0.0
  test: ^1.21.6
  test_process: ^2.0.0
