name: google_cloud_e2e
description: End-to-end validation for the google_cloud package.
publish_to: none
resolution:  workspace

environment:
  sdk: ^3.7.0

dependencies:
  google_cloud: any
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.2.0
  test: ^1.25.0
