name: fullstack_demo_frontend
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  json_annotation: ^4.9.0
  provider: ^6.0.0

dev_dependencies:
  build_runner: ^2.2.1
  dart_flutter_team_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  assets:
    - assets/config/
  uses-material-design: true
