name: __json__
description: A sample Functions Framework project for handling JSON.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  functions_framework: ^0.4.2
  json_annotation: ^4.9.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: ^2.2.1
  functions_framework_builder: ^0.4.8
  http: ^1.0.0
  json_serializable: ^6.8.0 
  dart_flutter_team_lints: ^3.0.0
  test: ^1.21.6
  test_process: ^2.0.0
