name: example_json_function
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  functions_framework: any
  json_annotation: ^3.1.1
  shelf: ^0.7.9

dev_dependencies:
  build_runner: ^1.10.2
  build_verify: ^1.1.1
  functions_framework_builder: any
  http: ^0.12.0
  json_serializable: ^3.5.1
  test: ^1.15.0
  test_process: ^1.0.0

dependency_overrides:
  functions_framework:
    path: ../../functions_framework
  functions_framework_builder:
    path: ../../functions_framework_builder
