name: example_json_function
version: 0.4.0
description: Dart Functions Framework simple JSON function example.
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  functions_framework: ^0.4.0
  json_annotation: ^4.8.1
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  http: '>=0.13.0 <2.0.0'
  json_serializable: ^6.0.0
  test: ^1.15.7
  test_process: ^2.0.0
