name: example_raw_cloudevent_function
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: ^2.6.0
  dart_flutter_team_lints: ^3.2.0
  functions_framework_builder: ^0.4.1
  http: ^1.1.0
  test: ^1.25.9
  test_process: ^2.0.3
