name: __projectName__
description: A sample Functions Framework project for handling a cloudevent.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  http: ^1.0.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
  test_process: ^2.0.0
