name: frontend_cli
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

executables:
  greet:

dependencies:
  http: ^1.1.0
  io: ^1.0.3
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.6.0
  dart_flutter_team_lints: ^3.2.0
  json_serializable: ^6.10.0
  test: ^1.25.9
