name: dartfn
description: >
  A tools package for managing FaaS (Function as a service) portable Dart functions projects
# After changing the version, run `pub run build_runner build`.
version: 0.4.7-wip
homepage: https://github.com/GoogleCloudPlatform/functions-framework-dart

resolution: workspace
environment:
  sdk: ^3.9.0

executables:
  dartfn:

dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  http: ^1.1.0
  io: ^1.0.3
  path: ^1.9.0

dev_dependencies:
  build: ^4.0.3
  build_config: ^1.2.0
  build_runner: ^2.10.4
  build_verify: ^3.0.0
  build_version: ^2.1.3
  dart_flutter_team_lints: ^3.2.0
  glob: ^2.1.2
  grinder: ^0.9.0
  source_gen: ^4.1.1
  test: ^1.27.0
  yaml: ^3.1.3
