name: dartfn
description: >
  A tools package for managing FaaS (Function as a service) portable Dart functions projects
# After changing the version, run `pub run build_runner build`.
version: 0.4.2
homepage: https://github.com/GoogleCloudPlatform/functions-framework-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  dartfn:

dependencies:
  args: ^2.1.1
  collection: ^1.15.0
  http: ^0.13.3
  io: ^1.0.0
  path: ^1.7.0
  usage: ^4.0.2

dev_dependencies:
  build: ^2.0.0
  build_config: ^1.0.0
  build_runner: ^2.0.4
  build_verify: ^2.0.0
  build_version: '>=2.0.1 <2.1.0'
  glob: ^2.0.0
  grinder: ^0.9.0
  lints: ^1.0.0
  source_gen: ^1.0.0
  test: ^1.15.7
  yaml: ^3.1.0
